spring.application.name=wegoauthentic

spring.datasource.url=jdbc:postgresql://localhost:5432/wegoauthentic
spring.datasource.username=postgres
spring.datasource.password=sulthan
spring.datasource.driver=org.postgresql.Driver
spring.redis.host=localhost
spring.redis.port=6379  