spring.application.name=wegoauthentic

spring.datasource.url=jdbc:postgresql://localhost:5432/wegoauthentic
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver=org.postgresql.Driver